leftnav:
- identifier: 23ab6fba-4820-bec2-ca5f-3c17ddaba8c4
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 1437967b-f352-b56a-9518-4ef89634d420
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 51795f47-b0a7-27bc-c98c-3f74c8795b64
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: dd51333a-871a-a8d2-b40f-47b66e6eaf39
  name: Readings
  url: /pages/readings
  weight: 40
